/*


 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.TaiKhoanDAO;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import model.TaiKhoanDTO;

/**
 *
 * @author truongthanh
 */
public class DangNhap extends javax.swing.JFrame {

    TaiKhoanDAO tkDAO = new TaiKhoanDAO();
    private ArrayList<TaiKhoanDTO> list_TK;
    // DefaultTableModel model_TaiKhoan;
    private Connection conn;

    /**
     * Creates new form DangNhap
     */
    public DangNhap() {
        initComponents();
        //jPanel3.setBackground(new Color (0,0,0,0)); 
        //jTextField1.setBackground(new Color (20,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jpnlManHinhDangNhap = new javax.swing.JPanel();
        jbtnQuenMatKhau = new javax.swing.JButton();
        jbtnDangKyTaiKhoan = new javax.swing.JButton();
        btnDangNhap = new javax.swing.JButton();
        jtxtMatKhau = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtTaiKhoan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jchkNhoMatKhau = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jpnlQuenMatKhau = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtxtTenDangNhap_QuenMatKhau = new javax.swing.JTextField();
        jtxtCauHoiBaoMat_QuenMatKhau = new javax.swing.JTextField();
        jtxtTraLoiCauHoi_QuenMatKhau = new javax.swing.JTextField();
        jtxtMatKhauMoi_FrmQuenMatKhau = new javax.swing.JTextField();
        jbtnTimKiem_QuenMatKhau = new javax.swing.JButton();
        jbtnTroVeCuaQuenMatKhau = new javax.swing.JButton();
        jbtnKichHoat_QuenMatKhau = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jpnlManHinhDangKy = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtTenDangNhap_FrmDangKy = new javax.swing.JTextField();
        jbtnDangKy = new javax.swing.JButton();
        jbtnTroVe = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtxtCauHoiBaoMat = new javax.swing.JTextField();
        jtxtTraLoiCauHoi = new javax.swing.JTextField();
        jtxtTaoMatKhau_FrmDangKy = new javax.swing.JPasswordField();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(java.awt.SystemColor.controlDkShadow);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new java.awt.CardLayout());

        jpnlManHinhDangNhap.setBackground(new java.awt.Color(245, 245, 245));
        jpnlManHinhDangNhap.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnQuenMatKhau.setBackground(new java.awt.Color(245, 245, 245));
        jbtnQuenMatKhau.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jbtnQuenMatKhau.setForeground(new java.awt.Color(225, 11, 11));
        jbtnQuenMatKhau.setText("Quên mật khẩu?");
        jbtnQuenMatKhau.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jbtnQuenMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnQuenMatKhauActionPerformed(evt);
            }
        });
        jpnlManHinhDangNhap.add(jbtnQuenMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 500, 90, -1));

        jbtnDangKyTaiKhoan.setBackground(new java.awt.Color(245, 245, 245));
        jbtnDangKyTaiKhoan.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jbtnDangKyTaiKhoan.setForeground(new java.awt.Color(225, 11, 11));
        jbtnDangKyTaiKhoan.setText("Đăng ký tài khoản >");
        jbtnDangKyTaiKhoan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jbtnDangKyTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDangKyTaiKhoanActionPerformed(evt);
            }
        });
        jpnlManHinhDangNhap.add(jbtnDangKyTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 500, 110, -1));

        btnDangNhap.setBackground(new java.awt.Color(114, 37, 255));
        btnDangNhap.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnDangNhap.setText("Đăng Nhập");
        btnDangNhap.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangNhap.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        jpnlManHinhDangNhap.add(btnDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, 180, 40));

        jtxtMatKhau.setBackground(new java.awt.Color(245, 245, 245));
        jtxtMatKhau.setText("aaaaaaaaaaaaaaa");
        jtxtMatKhau.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(250, 24, 24)));
        jtxtMatKhau.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtMatKhauFocusGained(evt);
            }
        });
        jtxtMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtMatKhauActionPerformed(evt);
            }
        });
        jpnlManHinhDangNhap.add(jtxtMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, 250, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("QUẢN LÝ BÁN THIẾT BỊ ĐIỆN TỬ");
        jpnlManHinhDangNhap.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Tên Đăng Nhập");
        jpnlManHinhDangNhap.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 120, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Mật Khẩu");
        jpnlManHinhDangNhap.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, 90, 20));

        jtxtTaiKhoan.setBackground(new java.awt.Color(245, 245, 245));
        jtxtTaiKhoan.setText("UserName");
        jtxtTaiKhoan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(250, 24, 24)));
        jtxtTaiKhoan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtTaiKhoanFocusGained(evt);
            }
        });
        jtxtTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTaiKhoanActionPerformed(evt);
            }
        });
        jpnlManHinhDangNhap.add(jtxtTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 250, 30));

        jLabel6.setFont(new java.awt.Font("Ravie", 1, 20)); // NOI18N
        jLabel6.setText("welcome to wibu");
        jpnlManHinhDangNhap.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 280, 70));

        jchkNhoMatKhau.setBackground(new java.awt.Color(245, 245, 245));
        jchkNhoMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jchkNhoMatKhau.setForeground(new java.awt.Color(21, 148, 193));
        jchkNhoMatKhau.setText("Nhớ mật khẩu");
        jpnlManHinhDangNhap.add(jchkNhoMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, -1, 20));

        jButton3.setBackground(new java.awt.Color(245, 245, 245));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 51));
        jButton3.setText("X");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jpnlManHinhDangNhap.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 330, 20, 20));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Thinh Ly\\Desktop\\Pic_Icon_Java\\aa.jpg")); // NOI18N
        jpnlManHinhDangNhap.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 740));

        jLabel15.setFont(new java.awt.Font("Ravie", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(7, 200, 105));
        jLabel15.setText("WiBu-Team");
        jpnlManHinhDangNhap.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 170, 50));

        jPanel3.add(jpnlManHinhDangNhap, "card3");

        jpnlQuenMatKhau.setBackground(new java.awt.Color(255, 255, 255));
        jpnlQuenMatKhau.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Tên Đăng Nhập");
        jpnlQuenMatKhau.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 110, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Câu Hỏi Bảo Mật");
        jpnlQuenMatKhau.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Trả Lời Câu Hỏi Bảo Mật");
        jpnlQuenMatKhau.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Mật Khẩu Mới");
        jpnlQuenMatKhau.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, -1, -1));

        jtxtTenDangNhap_QuenMatKhau.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jpnlQuenMatKhau.add(jtxtTenDangNhap_QuenMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 260, 40));

        jtxtCauHoiBaoMat_QuenMatKhau.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jpnlQuenMatKhau.add(jtxtCauHoiBaoMat_QuenMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 260, 40));

        jtxtTraLoiCauHoi_QuenMatKhau.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jpnlQuenMatKhau.add(jtxtTraLoiCauHoi_QuenMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 260, 40));

        jtxtMatKhauMoi_FrmQuenMatKhau.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jpnlQuenMatKhau.add(jtxtMatKhauMoi_FrmQuenMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, 260, 40));

        jbtnTimKiem_QuenMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnTimKiem_QuenMatKhau.setText("Tìm Kiếm...");
        jbtnTimKiem_QuenMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTimKiem_QuenMatKhauActionPerformed(evt);
            }
        });
        jpnlQuenMatKhau.add(jbtnTimKiem_QuenMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, -1, 30));

        jbtnTroVeCuaQuenMatKhau.setBackground(new java.awt.Color(3, 58, 58));
        jbtnTroVeCuaQuenMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jbtnTroVeCuaQuenMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        jbtnTroVeCuaQuenMatKhau.setText("<<");
        jbtnTroVeCuaQuenMatKhau.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jbtnTroVeCuaQuenMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTroVeCuaQuenMatKhauActionPerformed(evt);
            }
        });
        jpnlQuenMatKhau.add(jbtnTroVeCuaQuenMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 30));

        jbtnKichHoat_QuenMatKhau.setBackground(new java.awt.Color(97, 200, 13));
        jbtnKichHoat_QuenMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnKichHoat_QuenMatKhau.setText("Kích Hoạt");
        jbtnKichHoat_QuenMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKichHoat_QuenMatKhauActionPerformed(evt);
            }
        });
        jpnlQuenMatKhau.add(jbtnKichHoat_QuenMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, 200, 50));

        jLabel21.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel21.setText("Quên Mật Khẩu..");
        jLabel21.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(97, 200, 13)));
        jpnlQuenMatKhau.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 290, 50));

        jLabel22.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel22.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(97, 200, 13)));
        jpnlQuenMatKhau.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 60, 320));

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\Thinh Ly\\Desktop\\Pic_Icon_Java\\66fa983274830a826f6d88768dc403f4.jpg")); // NOI18N
        jpnlQuenMatKhau.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 430, 530));

        jPanel3.add(jpnlQuenMatKhau, "card4");

        jpnlManHinhDangKy.setBackground(new java.awt.Color(255, 255, 255));
        jpnlManHinhDangKy.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Tên Đăng Nhập");
        jpnlManHinhDangKy.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Tạo Mật Khẩu");
        jpnlManHinhDangKy.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, -1, -1));

        jtxtTenDangNhap_FrmDangKy.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 153, 153)));
        jpnlManHinhDangKy.add(jtxtTenDangNhap_FrmDangKy, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 130, 30));

        jbtnDangKy.setBackground(new java.awt.Color(97, 200, 13));
        jbtnDangKy.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnDangKy.setText("Đăng Ký");
        jbtnDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDangKyActionPerformed(evt);
            }
        });
        jpnlManHinhDangKy.add(jbtnDangKy, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 230, 50));

        jbtnTroVe.setBackground(new java.awt.Color(3, 58, 58));
        jbtnTroVe.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jbtnTroVe.setForeground(new java.awt.Color(255, 255, 255));
        jbtnTroVe.setText("<<");
        jbtnTroVe.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jbtnTroVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTroVeActionPerformed(evt);
            }
        });
        jpnlManHinhDangKy.add(jbtnTroVe, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Câu Hỏi Bảo Mật");
        jpnlManHinhDangKy.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Trả Lời Câu Hỏi");
        jpnlManHinhDangKy.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, -1, -1));

        jtxtCauHoiBaoMat.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 153, 153)));
        jpnlManHinhDangKy.add(jtxtCauHoiBaoMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 290, 30));

        jtxtTraLoiCauHoi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 153, 153)));
        jpnlManHinhDangKy.add(jtxtTraLoiCauHoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 290, 30));

        jtxtTaoMatKhau_FrmDangKy.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 153, 153)));
        jpnlManHinhDangKy.add(jtxtTaoMatKhau_FrmDangKy, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, 130, 30));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel19.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(97, 200, 13)));
        jpnlManHinhDangKy.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 60, 320));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel18.setText("Đăng Ký Tài Khoản..");
        jLabel18.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(97, 200, 13)));
        jpnlManHinhDangKy.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 290, 50));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\Thinh Ly\\Desktop\\Pic_Icon_Java\\66fa983274830a826f6d88768dc403f4.jpg")); // NOI18N
        jpnlManHinhDangKy.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 430, 530));

        jPanel3.add(jpnlManHinhDangKy, "card4");

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
//        String taikhoan = jtxtTaiKhoan.getText();
//        String matkhau = new String(jtxtMatKhau.getPassword());
        StringBuilder sb = new StringBuilder();
//        
        if (jchkNhoMatKhau.isSelected()) {
            JOptionPane.showMessageDialog(this, "Login information is remember");
        }
        // StringBuilder nb = new StringBuilder();
        if (jtxtTaiKhoan.equals("")) {
            sb.append("user is empty ");

        }
        if (jtxtMatKhau.equals("")) {
            sb.append("password is empty ");

        }
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb.toString(), "loi",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        TaiKhoanDAO dao = new TaiKhoanDAO();
        try {
            TaiKhoanDTO taikhoan = dao.checkTaiKhoan(jtxtTaiKhoan.getText(), new String(jtxtMatKhau.getPassword()));
            if (jtxtTaiKhoan.getText().isEmpty() || jtxtMatKhau.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập tên đăng nhập và mật khẩu đầy đủ");
                return;
            }
            if (taikhoan == null) {
                JOptionPane.showMessageDialog(this, "Tên đăng nhập hoặc mật khẩu sai");

            } else {
                manHinhChinh temp_form = new manHinhChinh();
                temp_form.setVisible(true);
                this.setVisible(false);
                this.dispose();
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi");
        }


    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void jtxtMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtMatKhauActionPerformed

    private void jtxtTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTaiKhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTaiKhoanActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jtxtTaiKhoan.setText("");
        jtxtMatKhau.setText("");
        jchkNhoMatKhau.setSelected(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jbtnDangKyTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDangKyTaiKhoanActionPerformed
        // TODO add your handling code here:
        jpnlManHinhDangKy.setVisible(true);
        jpnlManHinhDangNhap.setVisible(false);
    }//GEN-LAST:event_jbtnDangKyTaiKhoanActionPerformed

    private void XuatThongTinQuenMatKhau() {
        jtxtTenDangNhap_QuenMatKhau.setText("");
        jtxtCauHoiBaoMat_QuenMatKhau.setText("");
        jtxtTraLoiCauHoi_QuenMatKhau.setText("");
        jtxtMatKhauMoi_FrmQuenMatKhau.setText("");
    }

    private void XuatThongTinDangKy() {
        jtxtTenDangNhap_FrmDangKy.setText("");
        jtxtTaoMatKhau_FrmDangKy.setText("");
        jtxtCauHoiBaoMat.setText("");
        jtxtTraLoiCauHoi.setText("");
    }
    private void jbtnDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDangKyActionPerformed

        TaiKhoanDTO l = new TaiKhoanDTO();
        l.setTenDangNhap(jtxtTenDangNhap_FrmDangKy.getText());
        l.setMatKhau(jtxtTaoMatKhau_FrmDangKy.getText());
        l.setCauHoiBaoMat(jtxtCauHoiBaoMat.getText());
        l.setTraLoiCauHoi(jtxtTraLoiCauHoi.getText());
        if (jtxtTenDangNhap_FrmDangKy.getText().isEmpty() || jtxtTaoMatKhau_FrmDangKy.getText().isEmpty()
                || jtxtCauHoiBaoMat.getText().isEmpty() || jtxtTraLoiCauHoi.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhâp thông tin đầy đủ");
            return;
        }
        if (tkDAO.AddTaiKhoan(l)) {

            JOptionPane.showMessageDialog(rootPane, "Đã thêm thông tin thành công!");
            // list_TK.add(l); // them vao loai san pham
        } else {
            JOptionPane.showMessageDialog(rootPane, "Lỗi không thể thêm thông tin!");
        }
        XuatThongTinDangKy();
    }//GEN-LAST:event_jbtnDangKyActionPerformed

    private void jbtnTroVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTroVeActionPerformed
        // TODO add your handling code here:
        jpnlManHinhDangKy.setVisible(false);
        jpnlManHinhDangNhap.setVisible(true);
    }//GEN-LAST:event_jbtnTroVeActionPerformed

    private void jbtnKichHoat_QuenMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnKichHoat_QuenMatKhauActionPerformed
        String username = jtxtTenDangNhap_QuenMatKhau.getText();
        String newpassword = jtxtMatKhauMoi_FrmQuenMatKhau.getText();
        String CauHoiBaoMat = jtxtCauHoiBaoMat_QuenMatKhau.getText();
        String TraLoiCauHoi = jtxtTraLoiCauHoi_QuenMatKhau.getText();

        try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databasename=QLTBDT;"
                    + "username=sa;password=123;encrypt=true;trustServerCertificate=true");
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("select *from TaiKhoan where TenDangNhap ='" + username + "'and TraLoiCauHoi ='" + TraLoiCauHoi + "'");
            if (jtxtTenDangNhap_QuenMatKhau.getText().isEmpty() || jtxtCauHoiBaoMat_QuenMatKhau.getText().isEmpty()
                    || jtxtTraLoiCauHoi_QuenMatKhau.getText().isEmpty() || jtxtMatKhauMoi_FrmQuenMatKhau.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "vui long nhap day du thong tin");
                return;
            }
            if (rs.next()) {
                st.executeUpdate("update TaiKhoan set MatKhau= '" + newpassword + "'where TenDangNhap ='" + username + "'and TraLoiCauHoi='" + TraLoiCauHoi + "'");

                JOptionPane.showMessageDialog(null, "Mật khẩu của bạn đã được đổi thành công");

            } else {
                JOptionPane.showMessageDialog(null, "Xin vui lòng bạn trả lời thông tin chính xác");

            }
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, "Loi khong the ket noi");
            e.printStackTrace();
        }

        XuatThongTinQuenMatKhau();
    }//GEN-LAST:event_jbtnKichHoat_QuenMatKhauActionPerformed

    private void jbtnTimKiem_QuenMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTimKiem_QuenMatKhauActionPerformed
        String username = jtxtTenDangNhap_QuenMatKhau.getText();

        try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databasename=QLTBDT;"
                    + "username=sa;password=123;encrypt=true;trustServerCertificate=true");
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("select CauHoiBaoMat from TaiKhoan where TenDangNhap ='" + username + "'");
            if (rs.next()) {
                jtxtCauHoiBaoMat_QuenMatKhau.setText(rs.getString(1));

            } else {
                JOptionPane.showMessageDialog(null, "Vui lòng bạn trả lời chính xác tên đăng nhập");
                conn.close();
                rs.close();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jbtnTimKiem_QuenMatKhauActionPerformed

    private void jbtnTroVeCuaQuenMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTroVeCuaQuenMatKhauActionPerformed
        setVisible(false);
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        } catch (Exception e) {
            System.out.println(e);
        }
        new DangNhap().setVisible(true);
    }//GEN-LAST:event_jbtnTroVeCuaQuenMatKhauActionPerformed

    private void jbtnQuenMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnQuenMatKhauActionPerformed
        jpnlManHinhDangKy.setVisible(false);
        jpnlManHinhDangNhap.setVisible(false);
        jpnlQuenMatKhau.setVisible(true);
    }//GEN-LAST:event_jbtnQuenMatKhauActionPerformed

    private void jtxtMatKhauFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtMatKhauFocusGained
        // TODO add your handling code here:
        jtxtMatKhau.setText("");

    }//GEN-LAST:event_jtxtMatKhauFocusGained

    private void jtxtTaiKhoanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtTaiKhoanFocusGained
        // TODO add your handling code here:
        jtxtTaiKhoan.setText("");

    }//GEN-LAST:event_jtxtTaiKhoanFocusGained

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbtnDangKy;
    private javax.swing.JButton jbtnDangKyTaiKhoan;
    private javax.swing.JButton jbtnKichHoat_QuenMatKhau;
    private javax.swing.JButton jbtnQuenMatKhau;
    private javax.swing.JButton jbtnTimKiem_QuenMatKhau;
    private javax.swing.JButton jbtnTroVe;
    private javax.swing.JButton jbtnTroVeCuaQuenMatKhau;
    private javax.swing.JCheckBox jchkNhoMatKhau;
    private javax.swing.JPanel jpnlManHinhDangKy;
    private javax.swing.JPanel jpnlManHinhDangNhap;
    private javax.swing.JPanel jpnlQuenMatKhau;
    private javax.swing.JTextField jtxtCauHoiBaoMat;
    private javax.swing.JTextField jtxtCauHoiBaoMat_QuenMatKhau;
    private javax.swing.JPasswordField jtxtMatKhau;
    private javax.swing.JTextField jtxtMatKhauMoi_FrmQuenMatKhau;
    private javax.swing.JTextField jtxtTaiKhoan;
    private javax.swing.JPasswordField jtxtTaoMatKhau_FrmDangKy;
    private javax.swing.JTextField jtxtTenDangNhap_FrmDangKy;
    private javax.swing.JTextField jtxtTenDangNhap_QuenMatKhau;
    private javax.swing.JTextField jtxtTraLoiCauHoi;
    private javax.swing.JTextField jtxtTraLoiCauHoi_QuenMatKhau;
    // End of variables declaration//GEN-END:variables
}
